
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'c:\Users\riccardo.conventi\Desktop\SFCC_cleanpub\cleanpub\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface XXXXX {
			/**
			* XXXXX

				XXXXX
			* @group XXXXX - XXXXX
			* @source [attribute](file:c:\Users\riccardo.conventi\Desktop\SFCC_cleanpub\cleanpub\system-objecttype-extensions.xml#5) | [group](file:c:\Users\riccardo.conventi\Desktop\SFCC_cleanpub\cleanpub\system-objecttype-extensions.xml#27)
			*/
			XXXXX: string | null;

			/**
			* XXXXX

				XXXXX
			* @group XXXXX - XXXXX
			* @source [attribute](file:c:\Users\riccardo.conventi\Desktop\SFCC_cleanpub\cleanpub\system-objecttype-extensions.xml#13) | [group](file:c:\Users\riccardo.conventi\Desktop\SFCC_cleanpub\cleanpub\system-objecttype-extensions.xml#27)
			*/
			XXXXX: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
		
	}
}